# Generated by Django 6.0.1 on 2026-01-24 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_friendrequest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_accepted',
            new_name='is_Friend',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests_got', to='user.userprofile'),
        ),
    ]
