# Generated by Django 6.0.1 on 2026-01-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_is_accepted_friendrequest_is_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
