# Generated by Django 6.0.1 on 2026-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_verifycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='send_at',
            new_name='date_send',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_Friend',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
    ]
