# Generated by Django 6.0.1 on 2026-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_is_completed_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('IN_PROGRESS', 'In-Progress'), ('COMPLETED', 'Completed')], default='INCOMPLETE'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('IN_PROGRESS', 'In-Progress'), ('COMPLETED', 'Completed')], default='INCOMPLETE'),
        ),
    ]
